spring.application.name=demo
server.port=8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/last
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true
jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000


# ======================
# Gmail SMTP
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hejiy2002@gmail.com
spring.mail.password=qrgdiehnmpgfovbs
spring.mail.protocol=smtp
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
spring.mail.from=hejiy2002@gmail.com


# Cloudinary
cloudinary.cloud-name=doopsfdwr
cloudinary.api-key=638859748674885
cloudinary.api-secret=5p7XFXAWHdC9sxox14WByNbAVmE